CREATE TABLE RECIPE (
    REZEPTID       INTEGER NOT NULL,
    REZEPTNAME     VARCHAR(50),
    BESCHREIBUNG   VARCHAR(255),

    PRIMARY KEY (REZEPTID,REZEPTNAME),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR),
);

/* Add dummy Zutat */

INSERT INTO RECIPE (REZEPTID, REZEPTNAME, BESCHREIBUNG) VALUES (99999999,'TestRezept','Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
