USE db967aaa55; /* Name of Database */

/* Create Beschraenkungstable */
CREATE TABLE BESCHRAENKUNGEN (
    BESCHRAENKUNGSID       INTEGER NOT NULL,
    BESCHRAENKUNGSNAME     VARCHAR(50),
    PRIMARY KEY (BESCHRAENKUNGSID)
);

/* Insert Beschraenkugnen + weitere Zutaten die vorher nicht gegeben waren*/
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B01, 'Laktose');
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B02, 'Weizen');
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B03, 'Gluten');
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B04, 'Stärke');
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B05, 'Karotte');
INSERT INTO BESCHRAENKUNGEN (BESCHRAENKUNGSID, BESCHRAENKUNGSNAME) VALUES (B06, 'Nuss');


/* Insert Zutaten, die vorher nicht gegeben waren */
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9901, 'Reis', 'Gramm', 1.0, 500, 103, 349, 74.1, 7.2);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9902, 'Lasagneplatten', 'Gramm', 1.0, 400, 103, 356, 71, 12);
INSERT INTO ZUTAT (ZUTATENNR, BEZEICHNUNG, EINHEIT, NETTOPREIS, BESTAND, lieferant, KALORIEN, KOHLENHYDRATE, PROTEIN) VALUES (9003, 'Muskat', 'Gramm', 1.0, 400, 103, 525, 49, 6);


--Zwischentabelle für die die Beschraenkungen der einzelnen Zutaten
Create Table ZWISCHENTABELLEZUTATBESCHRAENKUNG (
    ZUTATENNR              INTEGER NOT NULL,
    BESCHRAENKUNGSID       INTEGER NOT NULL,
  

    PRIMARY KEY (BESCHRAENKUNGSID, ZUTATENNR), 
    FOREIGN KEY (RBESCHRAENKUNGSID) REFERENCES BESCHRAENKUNGEN (BESCHRAENKUNGSID),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);

/* Insert Zwischentabelle für Beschränkungen einer Zutat */

INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (1005, B05);

INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (7043, B05);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (3001, B01);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (3002, B01);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (6408, B02);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (9908, B02);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (6408, B03);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (9908, B03);

INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (1011, B04);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (9901, B04);
INSERT INTO ZWISCHENTABELLEZUTATBESCHRAENKUNG (ZUTATENNR, BESCHRAENKUNGSID ) VALUES (9003, B06);



 COMMIT WORK;