USE db967aaa55; /* Name of Database */

INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K01, 'Vegan');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K02, 'Vegetarisch');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K03, 'Low Carb');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K04, 'Keto');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K05, 'High Protein');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K06, 'Frutarisch');

INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R0, K05);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R1, K0);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R0, K05);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R0, K05);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R0, K05);