USE db967aaa55; /* Name of Database */

INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K01, 'Vegan');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K02, 'Vegetarisch');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K03, 'Low Carb');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K04, 'Keto');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K05, 'High Protein');
INSERT INTO ERNAEHRUNGSKATEGORIEN (KATEGORIEID, KATEGORIENAME) VALUES (K06, 'Low Fat');

INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R0, K05);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R1, K06);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R2, K01);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R2, K06);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R3, K02);
INSERT INTO ZWISCHENKATEGORIEREZEPT (REZEPTID, KATEGORIEID) VALUES (R4, K01);