USE db967aaa55; 



/* Auswahl aller Rezepte einer bestimmten Ernährungskategorie */
SELECT R.REZEPTNAME
FROM RECIPIE R
JOIN KATEGORIEZUWEISUNG KZ ON R.REZEPTID = KZ.REZEPTID
JOIN ERNAEHRUNGSKATEGORIEN EK ON KZ.KATEGORIEID = EK.KATEGORIEID
WHERE EK.KATEGORIENAME = 'Vegan';

/* Berechnung der durchschnittlichen Nährwerte aller Bestellungen eines Kunden */
SELECT 
    AVG(Z.KALORIEN) AS DURCHSCHNITT_KALORIEN,
    AVG(Z.KOHLENHYDRATE) AS DURCHSCHNITT_KOHLENHYDRATE,
    AVG(Z.PROTEIN) AS DURCHSCHNITT_PROTEIN
FROM BESTELLUNGSPOSITION BP
JOIN ZUTAT Z ON BP.ZUTATENNR = Z.ZUTATENNR
WHERE BP.KUNDENID = 'K123';

/* Auswahl aller Zutaten, die bisher keinem Rezept zugeordnet sind */
SELECT Z.BEZEICHNUNG
FROM ZUTAT Z
LEFT JOIN ZUTATENZUWEISUNG ZZ ON Z.ZUTATENNR = ZZ.ZUTATENNR
WHERE ZZ.REZEPTID IS NULL;

/* Auswahl aller Rezepte, die eine bestimmte Kalorienmenge nicht überschreiten */
SELECT R.REZEPTNAME
FROM RECIPIE R
JOIN ZUTATENZUWEISUNG ZZ ON R.REZEPTID = ZZ.REZEPTID
JOIN ZUTAT Z ON ZZ.ZUTATENNR = Z.ZUTATENNR
GROUP BY R.REZEPTNAME
HAVING SUM(Z.KALORIEN) < 500;

/* Auswahl aller Rezepte, die weniger als fünf Zutaten enthalten */
SELECT R.REZEPTNAME
FROM RECIPIE R
JOIN ZUTATENZUWEISUNG ZZ ON R.REZEPTID = ZZ.REZEPTID
GROUP BY R.REZEPTNAME
HAVING COUNT(ZZ.ZUTATENNR) < 5;

/* Auswahl aller Rezepte mit < 5 Zutaten und einer bestimmten Ernährungskategorie */
SELECT R.REZEPTNAME
FROM RECIPIE R
JOIN ZUTATENZUWEISUNG ZZ ON R.REZEPTID = ZZ.REZEPTID
JOIN KATEGORIEZUWEISUNG KZ ON R.REZEPTID = KZ.REZEPTID
JOIN ERNAEHRUNGSKATEGORIEN EK ON KZ.KATEGORIEID = EK.KATEGORIEID
WHERE EK.KATEGORIENAME = 'Vegan'
GROUP BY R.REZEPTNAME
HAVING COUNT(ZZ.ZUTATENNR) < 5;




/* Auswahl aller Beschränkungen einer Zutat (Subselect) */
SELECT BESCHRAENKUNGSNAME
FROM BESCHRAENKUNGEN
WHERE BESCHRAENKUNGSID IN (
    SELECT BESCHRAENKUNGSID
    FROM ZWISCHENTABELLEZUTATBESCHRAENKUNG
    WHERE ZUTATENNR = 9902
);

/* Anzahl der Rezepte pro Ernährungskategorie (Aggregatfunktion) */
SELECT EK.KATEGORIENAME, COUNT(*) AS ANZAHL_REZEPTE
FROM KATEGORIEZUWEISUNG KZ
JOIN ERNAEHRUNGSKATEGORIEN EK ON KZ.KATEGORIEID = EK.KATEGORIEID
GROUP BY EK.KATEGORIENAME;

/* Alle Rezepte mit Zutaten, die eine bestimmte Beschränkung betreffen (INNER JOIN + Subselect) */
SELECT DISTINCT R.REZEPTNAME
FROM RECIPIE R
JOIN ZUTATENZUWEISUNG ZZ ON R.REZEPTID = ZZ.REZEPTID
WHERE ZZ.ZUTATENNR IN (
    SELECT ZUTATENNR
    FROM ZWISCHENTABELLEZUTATBESCHRAENKUNG
    WHERE BESCHRAENKUNGSID = 'B02'
);


/* Auswahl aller Zutaten eines Rezeptes nach Rezeptname */
/* Last minute CHange */
SELECT
  Z.BEZEICHNUNG,
  ZZ.MENGE,
  Z.EINHEIT
FROM ZUTAT Z
JOIN ZUTATENZUWEISUNG ZZ ON Z.ZUTATENNR = ZZ.ZUTATENNR
JOIN RECIPIE R ON ZZ.REZEPTID = R.REZEPTID
WHERE R.REZEPTNAME = 'Lachslasagne'
LIMIT 0, 25;
